name: Build

on:
  push:
    branches:
      - develop
  
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build
        working-directory: ./build
        run: |
            dotnet new tool-manifest
            dotnet tool install cake.tool
            dotnet tool install minver-cli
            dotnet cake
